print ("Quantas canetas quer comprar?")
nrCanetas = input()
print ("Quanto custa cada caneta?")
preco = input()
valorP = int(nrCanetas)*float(preco)
print ("Vai pagar ", valorP, " por ",nrCanetas, " canetas.")
